horn1: { soundbegin: 26284_elf_horn_low_v2-1.wav soundmain: 26284_elf_horn_low_v2-2.wav soundend: 26284_elf_horn_low_v2-3.wav range: 1000 offset: [ 0.55, 1.54 , 9.94 ] pitchvariation: 0 } 
horn2: { soundbegin: 26284_elf_horn_high_v2-1.wav soundmain: 26284_elf_horn_high_v2-2.wav soundend: 26284_elf_horn_high_v2-3.wav range: 1000 offset: [ -0.55, 1.54 , 9.94 ] pitchvariation: 0 } 
horn3: { soundbegin: 26284_elf_whistle_v2-1.wav soundmain: 26284_elf_whistle_v2-2.wav soundend: 26284_elf_whistle_v2-3.wav range: 200 offset: [ -0.55, 1.54 , 9.94 ] pitchvariation: 0 } 

