horn1: { soundbegin: 27673_en78_sn_start.wav soundmain: 27673_en78_sn_trwa.wav soundend: 27673_en78_sn_stop.wav range: 1000 pitchvariation: 0 offset: [ 0.72, 3.94, -6.61 ] } 
horn2: { soundbegin: 27673_en78_sw_start.wav soundmain: 27673_en78_sw_trwa.wav soundend: 27673_en78_sw_stop.wav range: 1000 pitchvariation: 0 offset: [ -0.72, 3.94, -6.61 ] }  
horn3: { soundbegin: 26284_impuls_klakson-start.wav soundmain: 26284_impuls_klakson-trwa.wav soundend: 26284_impuls_klakson-stop.wav range: 200 pitchvariation: 0 offset: [ 0.55, 1.54 , -9.94 ] } 
