horn1: { soundbegin: 26284_36wea_horn_low-start.wav soundmain: 26284_36wea_horn_low-trwa.wav soundend: 26284_36wea_horn_low-stop.wav range: 1000 pitchvariation: 0 offset: [ 0.72, 3.94, -6.61 ] } 
horn2: { soundbegin: 26284_36wea_horn_high-start.wav soundmain: 26284_36wea_horn_high-trwa.wav soundend: 26284_36wea_horn_high-stop.wav range: 1000 pitchvariation: 0 offset: [ -0.72, 3.94, -6.61 ] }
horn3: { soundbegin: 26284_impuls_klakson-start.wav soundmain: 26284_impuls_klakson-trwa.wav soundend: 26284_impuls_klakson-stop.wav range: 200 pitchvariation: 0 offset: [ 0.55, 1.54 , -9.94 ] }
