//silniki - dŸwiêk podstawowy
tractionmotor: { //710 hz/110 km/h
 amplitudeoffset: 0.3
 amplitudefactor: 0.8
 frequencyfactor: 0.308
 range: 135
 crossfade: 90
 placement: external
 sound1: silence1.wav pitch1: 1
 sound40: en57_motor_40.wav pitch40: 40
 sound70: en57_motor_70.wav pitch70: 70
 sound160: en57_motor_160.wav pitch160: 160
 sound300: en57_motor_300.wav pitch300: 300
 sound465: en57_motor_465.wav pitch465: 465
 sound600: en57_motor_600.wav pitch600: 600
 sound6000: silence1.wav pitch6000: 6000 }
//silniki - brzêczenie w œrodku silnikowego
engine: { 
 amplitudeoffset: 0.0
 amplitudefactor: 5.0
 frequencyfactor: 0.308
 range: 55
 crossfade: 90
 placement: internal
 sound1: silence1.wav pitch1: 1
 sound45: silence1.wav pitch45: 60
 sound50: en57_motor_52b.wav pitch50: 65
 sound60: en57_motor_52b.wav pitch60: 65
 sound70: silence1.wav pitch70: 70 }