runningnoise: {
 range: -1
 amplitudefactor: 0.4
 amplitudeoffset: 0.1
 crossfade: 95
 sound0: silence1.wav pitch0: 100
 sound10: en57_runningnoise_10.wav pitch10: 100
 sound20: en57_runningnoise_20.wav pitch20: 100
 sound40: en57_runningnoise_40.wav pitch40: 100
 sound60: en57_runningnoise_60.wav pitch60: 100
 sound80: en57_runningnoise_80.wav pitch80: 100
 sound100: en57_runningnoise_100.wav pitch100: 100
 sound200: en57_runningnoise_100.wav pitch200: 120 }
