wheel_clatter:  55.0 
-9.346  //oœ 1
{ sound0: en57_stukot_15a_1.wav pitch0: 0.6
 sound15: en57_stukot_15a_1.wav pitch15: 0.6
 sound25: en57_stukot_30_2.wav pitch25: 0.6
 sound60: en57_stukot_30_2.wav pitch60: 0.8
 sound90: en57_stukot_90c.wav pitch90: 0.9
 sound1060: silence1.wav pitch1060: 6.0
 crossfade: 80 }
-6.638 //oœ 2
{ sound0: en57_stukot_15b_1.wav pitch0: 0.6
 sound15: en57_stukot_15b_1.wav pitch15: 0.6
 sound25: en57_stukot_30_1.wav pitch25: 0.6
 sound60: en57_stukot_30_1.wav pitch60: 0.8
 sound90: en57_stukot_90b.wav pitch90: 0.9
 sound1060: silence1.wav pitch1060: 6.0
 crossfade: 80 }
6.638 //oœ 3
{ sound0: en57_stukot_15b_1.wav pitch0: 0.6
 sound15: en57_stukot_15b_1.wav pitch15: 0.6
 sound25: en57_stukot_30_1.wav pitch25: 0.6
 sound60: en57_stukot_30_1.wav pitch60: 0.8
 sound90: en57_stukot_90b.wav pitch90: 0.9
 sound1060: silence1.wav pitch1060: 6.0
 crossfade: 80 }
9.346 //oœ 4
{ sound0: en57_stukot_15a_1.wav pitch0: 0.6
 sound15: en57_stukot_15a_1.wav pitch15: 0.6
 sound25: en57_stukot_30_2.wav pitch25: 0.6
 sound60: en57_stukot_30_2.wav pitch60: 0.8
 sound90: en57_stukot_90c.wav pitch90: 0.9
 sound1060: silence1.wav pitch1060: 6.0
 crossfade: 80 } 
end